# site settings
title: Fysioblauw 2
subtitle: Documentatie
email: saltycodeproductions@gmail.com
description: Alle documentatie voor Fysioblauw 2 op een rijtje.
baseurl: "/Fysioblauw2.Documentation" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Salty Code Productions (KvK)

favicon: /assets/icons/favicon.ico
logo: /assets/icons/favicon.ico

street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  windows: https://www.microsoft.com/nl-nl/p/fysioblauw-2/9p182cmp77w1?rtc=1&activetab=pivot:overviewtab
  apple:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- .jekyll-cache
- Gemfile
- Gemfile.lock
